import { MalpasTeamInfo, MalpasFixture, MalpasPlayerStats, MalpasClubRecord } from '@/types/malpas';
import { Player } from '@/types/cricket';

export const MALPAS_TEAMS: Record<string, MalpasTeamInfo> = {
  '1st_xi': {
    id: '1st_xi',
    name: 'Malpas CC 1st XI',
    shortName: 'Malpas 1st',
    captain: 'Callum Andrews',
    league: 'Cheshire Cricket League',
    division: 'Division 4',
    description: 'Premier Saturday XI competing in the Cheshire Cricket League.',
  },
  '2nd_xi': {
    id: '2nd_xi',
    name: 'Malpas CC 2nd XI',
    shortName: 'Malpas 2nd',
    captain: 'Richard Wardle',
    league: 'Cheshire Cricket League',
    division: 'Division 4 Reserve',
    description: 'Saturday 2nd XI developing top talent and club stalwarts.',
  },
  'sunday_xi': {
    id: 'sunday_xi',
    name: 'Malpas CC Sunday XI',
    shortName: 'Malpas Sunday',
    captain: 'George Hughes',
    league: 'Friendly & Cup Fixtures',
    division: 'Cheshire Sunday Cup',
    description: 'Traditional Sunday friendly side playing village & cup matches.',
  },
};

export const MALPAS_PLAYERS_1ST_XI: Player[] = [
  { id: 'm1_1', name: 'Callum Andrews', battingHand: 'RHB', bowlingStyle: 'Right-arm Fast', isCaptain: true },
  { id: 'm1_2', name: 'Ben Wardle', battingHand: 'LHB', bowlingStyle: 'Right-arm Medium' },
  { id: 'm1_3', name: 'Edward Stockton', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm1_4', name: 'Oliver Flannery', battingHand: 'RHB', isWicketKeeper: true },
  { id: 'm1_5', name: 'Harry Hughes', battingHand: 'LHB', bowlingStyle: 'Left-arm Spin' },
  { id: 'm1_6', name: 'Dominic Dunning', battingHand: 'RHB', bowlingStyle: 'Right-arm Fast' },
  { id: 'm1_7', name: 'Joe Roberts', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium' },
  { id: 'm1_8', name: 'James Sadler', battingHand: 'LHB' },
  { id: 'm1_9', name: 'Archie Higgins', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm1_10', name: 'Matthew Barlow', battingHand: 'RHB', bowlingStyle: 'Left-arm Fast' },
  { id: 'm1_11', name: 'Thomas Dutton', battingHand: 'RHB' },
];

export const MALPAS_PLAYERS_2ND_XI: Player[] = [
  { id: 'm2_1', name: 'Richard Wardle', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium', isCaptain: true },
  { id: 'm2_2', name: 'Sam Evans', battingHand: 'RHB', isWicketKeeper: true },
  { id: 'm2_3', name: 'Charlie Davenport', battingHand: 'LHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm2_4', name: 'David Probert', battingHand: 'RHB' },
  { id: 'm2_5', name: 'Will Harrison', battingHand: 'RHB', bowlingStyle: 'Right-arm Fast' },
  { id: 'm2_6', name: 'Gavin Jones', battingHand: 'LHB', bowlingStyle: 'Left-arm Spin' },
  { id: 'm2_7', name: 'Nathan Griffiths', battingHand: 'RHB' },
  { id: 'm2_8', name: 'Jack Millington', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium' },
  { id: 'm2_9', name: 'Luke Williams', battingHand: 'RHB' },
  { id: 'm2_10', name: 'Peter Davies', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm2_11', name: 'Robbie Clutton', battingHand: 'LHB' },
];

export const MALPAS_PLAYERS_SUNDAY_XI: Player[] = [
  { id: 'ms_1', name: 'George Hughes', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium', isCaptain: true },
  { id: 'ms_2', name: 'Finlay Sadler', battingHand: 'RHB', isWicketKeeper: true },
  { id: 'ms_3', name: 'Alfie Stockton', battingHand: 'LHB', bowlingStyle: 'Right-arm Fast' },
  { id: 'ms_4', name: 'Harrison Leigh', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'ms_5', name: 'Oscar Barlow', battingHand: 'RHB' },
  { id: 'ms_6', name: 'Freddie Dutton', battingHand: 'LHB', bowlingStyle: 'Left-arm Medium' },
  { id: 'ms_7', name: 'Toby Millington', battingHand: 'RHB' },
  { id: 'ms_8', name: 'Max Probert', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'ms_9', name: 'Lewis Clutton', battingHand: 'RHB' },
  { id: 'ms_10', name: 'Rory Evans', battingHand: 'RHB' },
  { id: 'ms_11', name: 'Daniel Davies', battingHand: 'LHB' },
];

export const MALPAS_FIXTURES: MalpasFixture[] = [
  // 1st XI Fixtures & Results
  {
    id: 'f1_1',
    teamId: '1st_xi',
    opponent: 'Bowdon Vale CC 1st XI',
    date: '2026-08-08',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'upcoming',
  },
  {
    id: 'f1_2',
    teamId: '1st_xi',
    opponent: 'Chester County Officers 1st XI',
    date: '2026-08-01',
    time: '12:30',
    venue: 'Away',
    ground: 'Mannings Lane, Chester',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 4 wickets',
    malpasScore: '184-6 (38.2 ov)',
    opponentScore: '181-9 (40.0 ov)',
  },
  {
    id: 'f1_3',
    teamId: '1st_xi',
    opponent: 'Kerridge CC 1st XI',
    date: '2026-07-25',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 32 runs',
    malpasScore: '215-7 (40.0 ov)',
    opponentScore: '183 all out (37.4 ov)',
  },
  {
    id: 'f1_4',
    teamId: '1st_xi',
    opponent: 'Trafford Metrovics 1st XI',
    date: '2026-07-18',
    time: '12:30',
    venue: 'Away',
    ground: 'Moss Lane, Timperley',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Trafford Metrovics won by 3 wickets',
    malpasScore: '162 all out (36.1 ov)',
    opponentScore: '163-7 (37.5 ov)',
  },

  // 2nd XI Fixtures & Results
  {
    id: 'f2_1',
    teamId: '2nd_xi',
    opponent: 'Westminster Park 2nd XI',
    date: '2026-08-08',
    time: '13:00',
    venue: 'Away',
    ground: 'Westminster Park, Chester',
    competition: 'Cheshire League Reserve Div 4',
    status: 'upcoming',
  },
  {
    id: 'f2_2',
    teamId: '2nd_xi',
    opponent: 'Kerridge CC 2nd XI',
    date: '2026-08-01',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 5 wickets',
    malpasScore: '145-5 (32.1 ov)',
    opponentScore: '142-8 (40.0 ov)',
  },

  // Sunday XI Fixtures
  {
    id: 'fs_1',
    teamId: 'sunday_xi',
    opponent: 'Whitchurch CC Sunday XI',
    date: '2026-08-09',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'upcoming',
  },
  {
    id: 'fs_2',
    teamId: 'sunday_xi',
    opponent: 'Ellesmere CC Sunday XI',
    date: '2026-08-02',
    time: '13:30',
    venue: 'Away',
    ground: 'Mereside Oval, Ellesmere',
    competition: 'Cheshire Sunday Cup',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 18 runs',
    malpasScore: '198-6 (35.0 ov)',
    opponentScore: '180-9 (35.0 ov)',
  },
];

export const MALPAS_PLAYER_STATS: MalpasPlayerStats[] = [
  // 1st XI Top Performers
  {
    id: 'm1_1',
    name: 'Callum Andrews',
    teamId: '1st_xi',
    role: 'All-Rounder',
    matches: 12,
    innings: 12,
    runs: 482,
    highScore: '112*',
    battingAverage: 48.2,
    hundreds: 1,
    fifties: 3,
    oversBowled: 78,
    wickets: 22,
    bestBowling: '5-24',
    bowlingAverage: 14.8,
    economy: 4.1,
    catches: 8,
    stumpings: 0,
  },
  {
    id: 'm1_2',
    name: 'Ben Wardle',
    teamId: '1st_xi',
    role: 'Batsman',
    matches: 12,
    innings: 11,
    runs: 415,
    highScore: '89',
    battingAverage: 41.5,
    hundreds: 0,
    fifties: 4,
    oversBowled: 12,
    wickets: 3,
    bestBowling: '2-18',
    bowlingAverage: 22.0,
    economy: 5.5,
    catches: 6,
    stumpings: 0,
  },
  {
    id: 'm1_3',
    name: 'Edward Stockton',
    teamId: '1st_xi',
    role: 'Bowler',
    matches: 11,
    innings: 8,
    runs: 135,
    highScore: '34*',
    battingAverage: 22.5,
    hundreds: 0,
    fifties: 0,
    oversBowled: 84,
    wickets: 26,
    bestBowling: '6-31',
    bowlingAverage: 12.3,
    economy: 3.8,
    catches: 5,
    stumpings: 0,
  },
  {
    id: 'm1_4',
    name: 'Oliver Flannery',
    teamId: '1st_xi',
    role: 'Wicket Keeper',
    matches: 12,
    innings: 12,
    runs: 310,
    highScore: '68',
    battingAverage: 31.0,
    hundreds: 0,
    fifties: 2,
    oversBowled: 0,
    wickets: 0,
    bestBowling: '-',
    bowlingAverage: 0,
    economy: 0,
    catches: 14,
    stumpings: 4,
  },

  // 2nd XI Performers
  {
    id: 'm2_1',
    name: 'Richard Wardle',
    teamId: '2nd_xi',
    role: 'All-Rounder',
    matches: 10,
    innings: 10,
    runs: 340,
    highScore: '76*',
    battingAverage: 37.7,
    hundreds: 0,
    fifties: 3,
    oversBowled: 64,
    wickets: 18,
    bestBowling: '4-22',
    bowlingAverage: 16.1,
    economy: 4.5,
    catches: 7,
    stumpings: 0,
  },
  {
    id: 'm2_3',
    name: 'Charlie Davenport',
    teamId: '2nd_xi',
    role: 'Batsman',
    matches: 9,
    innings: 9,
    runs: 285,
    highScore: '64',
    battingAverage: 31.6,
    hundreds: 0,
    fifties: 2,
    oversBowled: 28,
    wickets: 8,
    bestBowling: '3-19',
    bowlingAverage: 18.2,
    economy: 5.2,
    catches: 4,
    stumpings: 0,
  },

  // Sunday XI Performers
  {
    id: 'ms_1',
    name: 'George Hughes',
    teamId: 'sunday_xi',
    role: 'All-Rounder',
    matches: 8,
    innings: 8,
    runs: 260,
    highScore: '84*',
    battingAverage: 43.3,
    hundreds: 0,
    fifties: 2,
    oversBowled: 42,
    wickets: 12,
    bestBowling: '3-15',
    bowlingAverage: 14.5,
    economy: 4.1,
    catches: 6,
    stumpings: 0,
  },
];

export const MALPAS_CLUB_RECORDS: MalpasClubRecord[] = [
  { category: 'Team High Score', recordTitle: 'Highest Innings Total', value: '312-5', holder: '1st XI', year: '2023', opponent: 'Kerridge CC' },
  { category: 'Individual High Score', recordTitle: 'Highest Individual Score', value: '154*', holder: 'Callum Andrews', year: '2024', opponent: 'Chester County Officers' },
  { category: 'Best Bowling Figures', recordTitle: 'Best Match Bowling', value: '8-19', holder: 'Edward Stockton', year: '2023', opponent: 'Bowdon Vale CC' },
  { category: 'Partnership Record', recordTitle: '1st Wicket Partnership', value: '204 runs', holder: 'C. Andrews & B. Wardle', year: '2024', opponent: 'Trafford Metrovics' },
  { category: 'Most Wickets in Season', recordTitle: 'Season Wicket Record', value: '48 wickets', holder: 'Edward Stockton', year: '2023' },
  { category: 'Most Runs in Season', recordTitle: 'Season Run Record', value: '845 runs', holder: 'Callum Andrews', year: '2024' },
];
