import { MalpasTeamInfo, MalpasFixture, MalpasPlayerStats, MalpasClubRecord, MalpasNewsArticle, SpinVsSeamBreakdown, SpinVsSeamCategoryStats } from '@/types/malpas';
import { Player } from '@/types/cricket';

export const MALPAS_TEAMS: Record<string, MalpasTeamInfo> = {
  '1st_xi': {
    id: '1st_xi',
    name: 'Malpas CC 1st XI',
    shortName: 'Malpas 1st',
    captain: 'Callum Andrews',
    league: 'Cheshire Cricket League',
    division: 'Division 4',
    description: 'Premier Saturday XI competing in the Cheshire Cricket League.',
  },
  '2nd_xi': {
    id: '2nd_xi',
    name: 'Malpas CC 2nd XI',
    shortName: 'Malpas 2nd',
    captain: 'Richard Wardle',
    league: 'Cheshire Cricket League',
    division: 'Division 4 Reserve',
    description: 'Saturday 2nd XI developing top talent and club stalwarts.',
  },
  'sunday_xi': {
    id: 'sunday_xi',
    name: 'Malpas CC Sunday XI',
    shortName: 'Malpas Sunday',
    captain: 'George Hughes',
    league: 'Friendly & Cup Fixtures',
    division: 'Cheshire Sunday Cup',
    description: 'Traditional Sunday friendly side playing village & cup matches.',
  },
};

export const MALPAS_PLAYERS_1ST_XI: Player[] = [
  { id: 'm1_1', name: 'Callum Andrews', battingHand: 'RHB', bowlingStyle: 'Right-arm Fast', isCaptain: true },
  { id: 'm1_2', name: 'Ben Wardle', battingHand: 'LHB', bowlingStyle: 'Right-arm Medium' },
  { id: 'm1_3', name: 'Edward Stockton', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm1_4', name: 'Oliver Flannery', battingHand: 'RHB', isWicketKeeper: true },
  { id: 'm1_5', name: 'Harry Hughes', battingHand: 'LHB', bowlingStyle: 'Left-arm Spin' },
  { id: 'm1_6', name: 'Dominic Dunning', battingHand: 'RHB', bowlingStyle: 'Right-arm Fast' },
  { id: 'm1_7', name: 'Joe Roberts', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium' },
  { id: 'm1_8', name: 'James Sadler', battingHand: 'LHB' },
  { id: 'm1_9', name: 'Archie Higgins', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm1_10', name: 'Matthew Barlow', battingHand: 'RHB', bowlingStyle: 'Left-arm Fast' },
  { id: 'm1_11', name: 'Thomas Dutton', battingHand: 'RHB' },
];

export const MALPAS_PLAYERS_2ND_XI: Player[] = [
  { id: 'm2_1', name: 'Richard Wardle', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium', isCaptain: true },
  { id: 'm2_2', name: 'Sam Evans', battingHand: 'RHB', isWicketKeeper: true },
  { id: 'm2_3', name: 'Charlie Davenport', battingHand: 'LHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm2_4', name: 'David Probert', battingHand: 'RHB' },
  { id: 'm2_5', name: 'Will Harrison', battingHand: 'RHB', bowlingStyle: 'Right-arm Fast' },
  { id: 'm2_6', name: 'Gavin Jones', battingHand: 'LHB', bowlingStyle: 'Left-arm Spin' },
  { id: 'm2_7', name: 'Nathan Griffiths', battingHand: 'RHB' },
  { id: 'm2_8', name: 'Jack Millington', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium' },
  { id: 'm2_9', name: 'Luke Williams', battingHand: 'RHB' },
  { id: 'm2_10', name: 'Peter Davies', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'm2_11', name: 'Robbie Clutton', battingHand: 'LHB' },
];

export const MALPAS_PLAYERS_SUNDAY_XI: Player[] = [
  { id: 'ms_1', name: 'George Hughes', battingHand: 'RHB', bowlingStyle: 'Right-arm Medium', isCaptain: true },
  { id: 'ms_2', name: 'Finlay Sadler', battingHand: 'RHB', isWicketKeeper: true },
  { id: 'ms_3', name: 'Alfie Stockton', battingHand: 'LHB', bowlingStyle: 'Right-arm Fast' },
  { id: 'ms_4', name: 'Harrison Leigh', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'ms_5', name: 'Oscar Barlow', battingHand: 'RHB' },
  { id: 'ms_6', name: 'Freddie Dutton', battingHand: 'LHB', bowlingStyle: 'Left-arm Medium' },
  { id: 'ms_7', name: 'Toby Millington', battingHand: 'RHB' },
  { id: 'ms_8', name: 'Max Probert', battingHand: 'RHB', bowlingStyle: 'Right-arm Spin' },
  { id: 'ms_9', name: 'Lewis Clutton', battingHand: 'RHB' },
  { id: 'ms_10', name: 'Rory Evans', battingHand: 'RHB' },
  { id: 'ms_11', name: 'Daniel Davies', battingHand: 'LHB' },
];

export const MALPAS_FIXTURES: MalpasFixture[] = [
  // ==========================================
  // 1st XI - Cheshire Cricket League Division 4 (2026 Season)
  // ==========================================
  {
    id: 'f1_18',
    teamId: '1st_xi',
    opponent: 'Bowdon Vale CC 1st XI',
    date: '2026-08-08',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'upcoming',
  },
  {
    id: 'f1_19',
    teamId: '1st_xi',
    opponent: 'Cheadle Hulme Ladybridge 1st XI',
    date: '2026-08-15',
    time: '12:30',
    venue: 'Away',
    ground: 'Meadow Barn Road, Cheadle',
    competition: 'Cheshire Cricket League Div 4',
    status: 'upcoming',
  },
  {
    id: 'f1_20',
    teamId: '1st_xi',
    opponent: 'Styal CC 1st XI',
    date: '2026-08-22',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'upcoming',
  },
  {
    id: 'f1_21',
    teamId: '1st_xi',
    opponent: 'Runcorn CC 1st XI',
    date: '2026-08-29',
    time: '12:30',
    venue: 'Away',
    ground: 'Muncaster Drive, Runcorn',
    competition: 'Cheshire Cricket League Div 4',
    status: 'upcoming',
  },
  {
    id: 'f1_22',
    teamId: '1st_xi',
    opponent: 'Wirral CC 1st XI',
    date: '2026-09-05',
    time: '12:30',
    venue: 'Away',
    ground: 'Thornton Common Road, Wirral',
    competition: 'Cheshire Cricket League Div 4',
    status: 'upcoming',
  },
  {
    id: 'f1_16',
    teamId: '1st_xi',
    opponent: 'Chester County Officers 1st XI',
    date: '2026-08-01',
    time: '12:30',
    venue: 'Away',
    ground: 'Mannings Lane, Chester',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 4 wickets',
    malpasScore: '184-6 (38.2 ov)',
    opponentScore: '181-9 (40.0 ov)',
  },
  {
    id: 'f1_15',
    teamId: '1st_xi',
    opponent: 'Kerridge CC 1st XI',
    date: '2026-07-25',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 32 runs',
    malpasScore: '215-7 (40.0 ov)',
    opponentScore: '183 all out (37.4 ov)',
  },
  {
    id: 'f1_14',
    teamId: '1st_xi',
    opponent: 'Trafford Metrovics 1st XI',
    date: '2026-07-18',
    time: '12:30',
    venue: 'Away',
    ground: 'Moss Lane, Timperley',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Trafford Metrovics won by 3 wickets',
    malpasScore: '162 all out (36.1 ov)',
    opponentScore: '163-7 (37.5 ov)',
  },
  {
    id: 'f1_13',
    teamId: '1st_xi',
    opponent: 'Prestbury CC 1st XI',
    date: '2026-07-11',
    time: '12:30',
    venue: 'Away',
    ground: 'The Oval, Prestbury',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 19 runs',
    malpasScore: '205-7 (40.0 ov)',
    opponentScore: '186-9 (40.0 ov)',
  },
  {
    id: 'f1_12',
    teamId: '1st_xi',
    opponent: 'Appleton CC 1st XI',
    date: '2026-07-04',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 8 wickets',
    malpasScore: '142-2 (29.1 ov)',
    opponentScore: '139 all out (36.5 ov)',
  },
  {
    id: 'f1_11',
    teamId: '1st_xi',
    opponent: 'Trafford Metrovics 1st XI',
    date: '2026-06-27',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 64 runs',
    malpasScore: '245-5 (40.0 ov)',
    opponentScore: '181 all out (38.2 ov)',
  },
  {
    id: 'f1_10',
    teamId: '1st_xi',
    opponent: 'Bowdon Vale CC 1st XI',
    date: '2026-06-20',
    time: '12:30',
    venue: 'Away',
    ground: 'Priory Park, Bowdon',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 4 wickets',
    malpasScore: '188-6 (37.4 ov)',
    opponentScore: '185-9 (40.0 ov)',
  },
  {
    id: 'f1_9',
    teamId: '1st_xi',
    opponent: 'Kingsley CC 1st XI',
    date: '2026-06-13',
    time: '12:30',
    venue: 'Away',
    ground: 'The Croft, Kingsley',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 15 runs',
    malpasScore: '210-9 (40.0 ov)',
    opponentScore: '195-8 (40.0 ov)',
  },
  {
    id: 'f1_8',
    teamId: '1st_xi',
    opponent: 'Wirral CC 1st XI',
    date: '2026-06-06',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 7 wickets',
    malpasScore: '168-3 (31.0 ov)',
    opponentScore: '164 all out (39.1 ov)',
  },
  {
    id: 'f1_7',
    teamId: '1st_xi',
    opponent: 'Kerridge CC 1st XI',
    date: '2026-05-30',
    time: '12:30',
    venue: 'Away',
    ground: 'Clarke Lane, Kerridge',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 3 wickets',
    malpasScore: '199-7 (39.2 ov)',
    opponentScore: '195-9 (40.0 ov)',
  },
  {
    id: 'f1_6',
    teamId: '1st_xi',
    opponent: 'Chester County Officers 1st XI',
    date: '2026-05-23',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 52 runs',
    malpasScore: '238-6 (40.0 ov)',
    opponentScore: '186 all out (36.4 ov)',
  },
  {
    id: 'f1_5',
    teamId: '1st_xi',
    opponent: 'Cheadle Hulme Ladybridge 1st XI',
    date: '2026-05-16',
    time: '12:30',
    venue: 'Away',
    ground: 'Meadow Barn Road, Cheadle',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 5 wickets',
    malpasScore: '178-5 (35.1 ov)',
    opponentScore: '174-8 (40.0 ov)',
  },
  {
    id: 'f1_4_early',
    teamId: '1st_xi',
    opponent: 'Runcorn CC 1st XI',
    date: '2026-05-09',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 28 runs',
    malpasScore: '201-8 (40.0 ov)',
    opponentScore: '173 all out (37.5 ov)',
  },
  {
    id: 'f1_3_early',
    teamId: '1st_xi',
    opponent: 'Styal CC 1st XI',
    date: '2026-05-02',
    time: '12:30',
    venue: 'Away',
    ground: 'Altrincham Road, Styal',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 6 wickets',
    malpasScore: '156-4 (33.0 ov)',
    opponentScore: '155-9 (40.0 ov)',
  },
  {
    id: 'f1_2_early',
    teamId: '1st_xi',
    opponent: 'Prestbury CC 1st XI',
    date: '2026-04-25',
    time: '12:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 45 runs',
    malpasScore: '224-5 (40.0 ov)',
    opponentScore: '179 all out (38.1 ov)',
  },
  {
    id: 'f1_1_early',
    teamId: '1st_xi',
    opponent: 'Appleton CC 1st XI',
    date: '2026-04-18',
    time: '12:30',
    venue: 'Away',
    ground: 'Lyons Lane, Appleton',
    competition: 'Cheshire Cricket League Div 4',
    status: 'completed',
    resultText: 'Malpas CC won by 4 wickets',
    malpasScore: '192-6 (38.4 ov)',
    opponentScore: '190-8 (40.0 ov)',
  },

  // ==========================================
  // 2nd XI - Cheshire League Reserve Division 4 (2026 Season)
  // ==========================================
  {
    id: 'f2_17',
    teamId: '2nd_xi',
    opponent: 'Westminster Park 2nd XI',
    date: '2026-08-08',
    time: '13:00',
    venue: 'Away',
    ground: 'Westminster Park, Chester',
    competition: 'Cheshire League Reserve Div 4',
    status: 'upcoming',
  },
  {
    id: 'f2_18',
    teamId: '2nd_xi',
    opponent: 'Bowdon Vale 2nd XI',
    date: '2026-08-15',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'upcoming',
  },
  {
    id: 'f2_19',
    teamId: '2nd_xi',
    opponent: 'Runcorn CC 2nd XI',
    date: '2026-08-22',
    time: '13:00',
    venue: 'Away',
    ground: 'Muncaster Drive, Runcorn',
    competition: 'Cheshire League Reserve Div 4',
    status: 'upcoming',
  },
  {
    id: 'f2_20',
    teamId: '2nd_xi',
    opponent: 'Kingsley CC 2nd XI',
    date: '2026-08-29',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'upcoming',
  },
  {
    id: 'f2_21',
    teamId: '2nd_xi',
    opponent: 'Prestbury CC 2nd XI',
    date: '2026-09-05',
    time: '13:00',
    venue: 'Away',
    ground: 'The Oval, Prestbury',
    competition: 'Cheshire League Reserve Div 4',
    status: 'upcoming',
  },
  {
    id: 'f2_16',
    teamId: '2nd_xi',
    opponent: 'Kerridge CC 2nd XI',
    date: '2026-08-01',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 5 wickets',
    malpasScore: '145-5 (32.1 ov)',
    opponentScore: '142-8 (40.0 ov)',
  },
  {
    id: 'f2_15',
    teamId: '2nd_xi',
    opponent: 'Wirral CC 2nd XI',
    date: '2026-07-25',
    time: '13:00',
    venue: 'Away',
    ground: 'Thornton Common Road, Wirral',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 21 runs',
    malpasScore: '188-7 (40.0 ov)',
    opponentScore: '167-9 (40.0 ov)',
  },
  {
    id: 'f2_14',
    teamId: '2nd_xi',
    opponent: 'Chester County Officers 2nd XI',
    date: '2026-07-18',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 6 wickets',
    malpasScore: '152-4 (33.5 ov)',
    opponentScore: '148 all out (38.1 ov)',
  },
  {
    id: 'f2_13',
    teamId: '2nd_xi',
    opponent: 'Irby CC 3rd XI',
    date: '2026-07-11',
    time: '13:00',
    venue: 'Away',
    ground: 'Mill Hill Road, Irby',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 4 wickets',
    malpasScore: '170-6 (36.2 ov)',
    opponentScore: '166-7 (40.0 ov)',
  },
  {
    id: 'f2_12',
    teamId: '2nd_xi',
    opponent: 'Irby CC 4th XI',
    date: '2026-07-04',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 58 runs',
    malpasScore: '212-5 (40.0 ov)',
    opponentScore: '154-8 (40.0 ov)',
  },
  {
    id: 'f2_11',
    teamId: '2nd_xi',
    opponent: 'Styal CC 2nd XI',
    date: '2026-06-27',
    time: '13:00',
    venue: 'Away',
    ground: 'Altrincham Road, Styal',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 2 wickets',
    malpasScore: '149-8 (39.1 ov)',
    opponentScore: '148 all out (37.4 ov)',
  },
  {
    id: 'f2_10',
    teamId: '2nd_xi',
    opponent: 'Prestbury CC 2nd XI',
    date: '2026-06-20',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 5 wickets',
    malpasScore: '160-5 (34.0 ov)',
    opponentScore: '156-9 (40.0 ov)',
  },
  {
    id: 'f2_9',
    teamId: '2nd_xi',
    opponent: 'Kingsley CC 2nd XI',
    date: '2026-06-13',
    time: '13:00',
    venue: 'Away',
    ground: 'The Croft, Kingsley',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 34 runs',
    malpasScore: '205-6 (40.0 ov)',
    opponentScore: '171-8 (40.0 ov)',
  },
  {
    id: 'f2_8',
    teamId: '2nd_xi',
    opponent: 'Runcorn CC 2nd XI',
    date: '2026-06-06',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 7 wickets',
    malpasScore: '139-3 (28.4 ov)',
    opponentScore: '135 all out (36.1 ov)',
  },
  {
    id: 'f2_7',
    teamId: '2nd_xi',
    opponent: 'Kerridge CC 2nd XI',
    date: '2026-05-30',
    time: '13:00',
    venue: 'Away',
    ground: 'Clarke Lane, Kerridge',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 18 runs',
    malpasScore: '175-7 (40.0 ov)',
    opponentScore: '157-9 (40.0 ov)',
  },
  {
    id: 'f2_6',
    teamId: '2nd_xi',
    opponent: 'Bowdon Vale 2nd XI',
    date: '2026-05-23',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 4 wickets',
    malpasScore: '166-6 (35.2 ov)',
    opponentScore: '162-8 (40.0 ov)',
  },
  {
    id: 'f2_5',
    teamId: '2nd_xi',
    opponent: 'Westminster Park 2nd XI',
    date: '2026-05-16',
    time: '13:00',
    venue: 'Away',
    ground: 'Westminster Park, Chester',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 25 runs',
    malpasScore: '182-8 (40.0 ov)',
    opponentScore: '157-9 (40.0 ov)',
  },
  {
    id: 'f2_4',
    teamId: '2nd_xi',
    opponent: 'Wirral CC 2nd XI',
    date: '2026-05-09',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 6 wickets',
    malpasScore: '148-4 (31.2 ov)',
    opponentScore: '144 all out (38.0 ov)',
  },
  {
    id: 'f2_3',
    teamId: '2nd_xi',
    opponent: 'Chester County Officers 2nd XI',
    date: '2026-05-02',
    time: '13:00',
    venue: 'Away',
    ground: 'Mannings Lane, Chester',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 3 wickets',
    malpasScore: '164-7 (37.1 ov)',
    opponentScore: '160-9 (40.0 ov)',
  },
  {
    id: 'f2_2_early',
    teamId: '2nd_xi',
    opponent: 'Irby CC 3rd XI',
    date: '2026-04-25',
    time: '13:00',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 42 runs',
    malpasScore: '195-6 (40.0 ov)',
    opponentScore: '153 all out (36.2 ov)',
  },
  {
    id: 'f2_1_early',
    teamId: '2nd_xi',
    opponent: 'Irby CC 4th XI',
    date: '2026-04-18',
    time: '13:00',
    venue: 'Away',
    ground: 'Mill Hill Road, Irby',
    competition: 'Cheshire League Reserve Div 4',
    status: 'completed',
    resultText: 'Malpas 2nd XI won by 5 wickets',
    malpasScore: '158-5 (34.0 ov)',
    opponentScore: '155-8 (40.0 ov)',
  },

  // ==========================================
  // Sunday XI - Cheshire Sunday Cup & Friendly (2026 Season)
  // ==========================================
  {
    id: 'fs_15',
    teamId: 'sunday_xi',
    opponent: 'Whitchurch CC Sunday XI',
    date: '2026-08-09',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'upcoming',
  },
  {
    id: 'fs_16',
    teamId: 'sunday_xi',
    opponent: 'Cholmondeley CC Sunday XI',
    date: '2026-08-16',
    time: '13:30',
    venue: 'Away',
    ground: 'Castle Park, Cholmondeley',
    competition: 'Cheshire Sunday Cup',
    status: 'upcoming',
  },
  {
    id: 'fs_17',
    teamId: 'sunday_xi',
    opponent: 'Oswestry CC Sunday XI',
    date: '2026-08-23',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'upcoming',
  },
  {
    id: 'fs_18',
    teamId: 'sunday_xi',
    opponent: 'Wem CC Sunday XI',
    date: '2026-08-30',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'upcoming',
  },
  {
    id: 'fs_14',
    teamId: 'sunday_xi',
    opponent: 'Ellesmere CC Sunday XI',
    date: '2026-08-02',
    time: '13:30',
    venue: 'Away',
    ground: 'Mereside Oval, Ellesmere',
    competition: 'Cheshire Sunday Cup',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 18 runs',
    malpasScore: '198-6 (35.0 ov)',
    opponentScore: '180-9 (35.0 ov)',
  },
  {
    id: 'fs_13',
    teamId: 'sunday_xi',
    opponent: 'Tarporley CC Sunday XI',
    date: '2026-07-12',
    time: '13:30',
    venue: 'Away',
    ground: 'Brook Street, Tarporley',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 3 wickets',
    malpasScore: '174-7 (33.2 ov)',
    opponentScore: '171-8 (35.0 ov)',
  },
  {
    id: 'fs_12',
    teamId: 'sunday_xi',
    opponent: 'Christleton CC Sunday XI',
    date: '2026-07-05',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 52 runs',
    malpasScore: '235-5 (35.0 ov)',
    opponentScore: '183-9 (35.0 ov)',
  },
  {
    id: 'fs_11',
    teamId: 'sunday_xi',
    opponent: 'Oxton CC Sunday XI',
    date: '2026-06-28',
    time: '13:30',
    venue: 'Away',
    ground: 'Townfield Lane, Oxton',
    competition: 'Cheshire Sunday Cup',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 6 wickets',
    malpasScore: '160-4 (30.1 ov)',
    opponentScore: '158 all out (34.2 ov)',
  },
  {
    id: 'fs_10',
    teamId: 'sunday_xi',
    opponent: 'Neston CC Sunday XI',
    date: '2026-06-21',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 28 runs',
    malpasScore: '218-6 (35.0 ov)',
    opponentScore: '190-8 (35.0 ov)',
  },
  {
    id: 'fs_9',
    teamId: 'sunday_xi',
    opponent: 'Chester Boughton Hall Sunday XI',
    date: '2026-06-14',
    time: '13:30',
    venue: 'Away',
    ground: 'Filkins Lane, Chester',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 4 wickets',
    malpasScore: '182-6 (34.0 ov)',
    opponentScore: '178-7 (35.0 ov)',
  },
  {
    id: 'fs_8',
    teamId: 'sunday_xi',
    opponent: 'Upton CC Sunday XI',
    date: '2026-06-07',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 15 runs',
    malpasScore: '205-8 (35.0 ov)',
    opponentScore: '190-9 (35.0 ov)',
  },
  {
    id: 'fs_7',
    teamId: 'sunday_xi',
    opponent: 'Caldy CC Sunday XI',
    date: '2026-05-31',
    time: '13:30',
    venue: 'Away',
    ground: 'Telegraph Road, Caldy',
    competition: 'Cheshire Sunday Cup',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 3 wickets',
    malpasScore: '192-7 (34.1 ov)',
    opponentScore: '188-8 (35.0 ov)',
  },
  {
    id: 'fs_6',
    teamId: 'sunday_xi',
    opponent: 'Audlem CC Sunday XI',
    date: '2026-05-24',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 62 runs',
    malpasScore: '240-4 (35.0 ov)',
    opponentScore: '178-9 (35.0 ov)',
  },
  {
    id: 'fs_5',
    teamId: 'sunday_xi',
    opponent: 'Wem CC Sunday XI',
    date: '2026-05-17',
    time: '13:30',
    venue: 'Away',
    ground: 'Soulton Road, Wem',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 5 wickets',
    malpasScore: '169-5 (32.4 ov)',
    opponentScore: '165-8 (35.0 ov)',
  },
  {
    id: 'fs_4',
    teamId: 'sunday_xi',
    opponent: 'Cholmondeley CC Sunday XI',
    date: '2026-05-10',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 48 runs',
    malpasScore: '225-6 (35.0 ov)',
    opponentScore: '177 all out (33.1 ov)',
  },
  {
    id: 'fs_3',
    teamId: 'sunday_xi',
    opponent: 'Oswestry CC Sunday XI',
    date: '2026-05-03',
    time: '13:30',
    venue: 'Away',
    ground: 'Morda Road, Oswestry',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 2 wickets',
    malpasScore: '186-8 (34.4 ov)',
    opponentScore: '184-7 (35.0 ov)',
  },
  {
    id: 'fs_2_early',
    teamId: 'sunday_xi',
    opponent: 'Ellesmere CC Sunday XI',
    date: '2026-04-26',
    time: '13:30',
    venue: 'Home',
    ground: 'The Recreation Ground, Wrexham Road, Malpas',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 35 runs',
    malpasScore: '210-5 (35.0 ov)',
    opponentScore: '175-9 (35.0 ov)',
  },
  {
    id: 'fs_1_early',
    teamId: 'sunday_xi',
    opponent: 'Whitchurch CC Sunday XI',
    date: '2026-04-19',
    time: '13:30',
    venue: 'Away',
    ground: 'Cricket Meadow, Whitchurch',
    competition: 'Sunday Friendly',
    status: 'completed',
    resultText: 'Malpas Sunday XI won by 4 wickets',
    malpasScore: '175-6 (33.1 ov)',
    opponentScore: '172-8 (35.0 ov)',
  },
];

export const MALPAS_PLAYER_STATS: MalpasPlayerStats[] = [
  // 1st XI Top Performers
  {
    id: 'm1_1',
    name: 'Callum Andrews',
    teamId: '1st_xi',
    role: 'All-Rounder',
    matches: 12,
    innings: 12,
    runs: 482,
    highScore: '112*',
    battingAverage: 48.2,
    hundreds: 1,
    fifties: 3,
    oversBowled: 78,
    wickets: 22,
    fiveWickets: 1,
    bestBowling: '5-24',
    bowlingAverage: 14.8,
    economy: 4.1,
    bowlingStyle: 'Right-arm fast-medium',
    bowlingType: 'seam',
    catches: 8,
    stumpings: 0,
  },
  {
    id: 'm1_2',
    name: 'Ben Wardle',
    teamId: '1st_xi',
    role: 'Batsman',
    matches: 12,
    innings: 11,
    runs: 415,
    highScore: '89',
    battingAverage: 41.5,
    hundreds: 0,
    fifties: 4,
    oversBowled: 12,
    wickets: 3,
    fiveWickets: 0,
    bestBowling: '2-18',
    bowlingAverage: 22.0,
    economy: 5.5,
    bowlingStyle: 'Right-arm medium',
    bowlingType: 'seam',
    catches: 6,
    stumpings: 0,
  },
  {
    id: 'm1_3',
    name: 'Edward Stockton',
    teamId: '1st_xi',
    role: 'Bowler',
    matches: 11,
    innings: 8,
    runs: 135,
    highScore: '34*',
    battingAverage: 22.5,
    hundreds: 0,
    fifties: 0,
    oversBowled: 84,
    wickets: 26,
    fiveWickets: 2,
    bestBowling: '6-31',
    bowlingAverage: 12.3,
    economy: 3.8,
    bowlingStyle: 'Right-arm off-spin',
    bowlingType: 'spin',
    catches: 5,
    stumpings: 0,
  },
  {
    id: 'm1_4',
    name: 'Oliver Flannery',
    teamId: '1st_xi',
    role: 'Wicket Keeper',
    matches: 12,
    innings: 12,
    runs: 310,
    highScore: '68',
    battingAverage: 31.0,
    hundreds: 0,
    fifties: 2,
    oversBowled: 0,
    wickets: 0,
    fiveWickets: 0,
    bestBowling: '-',
    bowlingAverage: 0,
    economy: 0,
    catches: 14,
    stumpings: 4,
  },
  {
    id: 'm1_6',
    name: 'Dominic Dunning',
    teamId: '1st_xi',
    role: 'Bowler',
    matches: 11,
    innings: 6,
    runs: 45,
    highScore: '18',
    battingAverage: 9.0,
    hundreds: 0,
    fifties: 0,
    oversBowled: 65,
    wickets: 19,
    fiveWickets: 1,
    bestBowling: '5-18',
    bowlingAverage: 13.4,
    economy: 3.9,
    bowlingStyle: 'Right-arm fast',
    bowlingType: 'seam',
    catches: 4,
    stumpings: 0,
  },
  {
    id: 'm1_5',
    name: 'Harry Hughes',
    teamId: '1st_xi',
    role: 'All-Rounder',
    matches: 10,
    innings: 8,
    runs: 185,
    highScore: '44',
    battingAverage: 26.4,
    hundreds: 0,
    fifties: 0,
    oversBowled: 52,
    wickets: 14,
    fiveWickets: 0,
    bestBowling: '4-28',
    bowlingAverage: 16.4,
    economy: 4.4,
    bowlingStyle: 'Left-arm orthodox spin',
    bowlingType: 'spin',
    catches: 6,
    stumpings: 0,
  },
  {
    id: 'm1_9',
    name: 'Archie Higgins',
    teamId: '1st_xi',
    role: 'Bowler',
    matches: 8,
    innings: 5,
    runs: 32,
    highScore: '12*',
    battingAverage: 10.7,
    hundreds: 0,
    fifties: 0,
    oversBowled: 36,
    wickets: 9,
    fiveWickets: 0,
    bestBowling: '3-22',
    bowlingAverage: 19.2,
    economy: 4.8,
    bowlingStyle: 'Right-arm leg-spin',
    bowlingType: 'spin',
    catches: 3,
    stumpings: 0,
  },

  // 2nd XI Performers
  {
    id: 'm2_1',
    name: 'Richard Wardle',
    teamId: '2nd_xi',
    role: 'All-Rounder',
    matches: 10,
    innings: 10,
    runs: 340,
    highScore: '76*',
    battingAverage: 37.7,
    hundreds: 0,
    fifties: 3,
    oversBowled: 64,
    wickets: 18,
    fiveWickets: 0,
    bestBowling: '4-22',
    bowlingAverage: 16.1,
    economy: 4.5,
    bowlingStyle: 'Right-arm fast-medium',
    bowlingType: 'seam',
    catches: 7,
    stumpings: 0,
  },
  {
    id: 'm2_3',
    name: 'Charlie Davenport',
    teamId: '2nd_xi',
    role: 'Batsman',
    matches: 9,
    innings: 9,
    runs: 285,
    highScore: '64',
    battingAverage: 31.6,
    hundreds: 0,
    fifties: 2,
    oversBowled: 28,
    wickets: 8,
    fiveWickets: 0,
    bestBowling: '3-19',
    bowlingAverage: 18.2,
    economy: 5.2,
    bowlingStyle: 'Left-arm orthodox spin',
    bowlingType: 'spin',
    catches: 4,
    stumpings: 0,
  },
  {
    id: 'm2_5',
    name: 'Will Harrison',
    teamId: '2nd_xi',
    role: 'Bowler',
    matches: 9,
    innings: 6,
    runs: 68,
    highScore: '22',
    battingAverage: 13.6,
    hundreds: 0,
    fifties: 0,
    oversBowled: 58,
    wickets: 16,
    fiveWickets: 1,
    bestBowling: '5-32',
    bowlingAverage: 15.5,
    economy: 4.3,
    bowlingStyle: 'Right-arm fast',
    bowlingType: 'seam',
    catches: 5,
    stumpings: 0,
  },
  {
    id: 'm2_6',
    name: 'Gavin Jones',
    teamId: '2nd_xi',
    role: 'Bowler',
    matches: 8,
    innings: 5,
    runs: 40,
    highScore: '15*',
    battingAverage: 10.0,
    hundreds: 0,
    fifties: 0,
    oversBowled: 44,
    wickets: 11,
    fiveWickets: 0,
    bestBowling: '4-30',
    bowlingAverage: 17.8,
    economy: 4.5,
    bowlingStyle: 'Left-arm orthodox spin',
    bowlingType: 'spin',
    catches: 3,
    stumpings: 0,
  },
  {
    id: 'm2_8',
    name: 'Jack Millington',
    teamId: '2nd_xi',
    role: 'All-Rounder',
    matches: 8,
    innings: 7,
    runs: 160,
    highScore: '45',
    battingAverage: 22.8,
    hundreds: 0,
    fifties: 0,
    oversBowled: 36,
    wickets: 10,
    fiveWickets: 0,
    bestBowling: '3-21',
    bowlingAverage: 17.1,
    economy: 4.75,
    bowlingStyle: 'Right-arm medium',
    bowlingType: 'seam',
    catches: 4,
    stumpings: 0,
  },
  {
    id: 'm2_10',
    name: 'Peter Davies',
    teamId: '2nd_xi',
    role: 'Bowler',
    matches: 7,
    innings: 4,
    runs: 28,
    highScore: '11',
    battingAverage: 7.0,
    hundreds: 0,
    fifties: 0,
    oversBowled: 32,
    wickets: 7,
    fiveWickets: 0,
    bestBowling: '2-28',
    bowlingAverage: 21.4,
    economy: 4.7,
    bowlingStyle: 'Right-arm off-spin',
    bowlingType: 'spin',
    catches: 2,
    stumpings: 0,
  },

  // Sunday XI Performers
  {
    id: 'ms_1',
    name: 'George Hughes',
    teamId: 'sunday_xi',
    role: 'All-Rounder',
    matches: 8,
    innings: 8,
    runs: 260,
    highScore: '84*',
    battingAverage: 43.3,
    hundreds: 0,
    fifties: 2,
    oversBowled: 42,
    wickets: 12,
    fiveWickets: 0,
    bestBowling: '3-15',
    bowlingAverage: 14.5,
    economy: 4.1,
    bowlingStyle: 'Right-arm medium',
    bowlingType: 'seam',
    catches: 6,
    stumpings: 0,
  },
  {
    id: 'ms_3',
    name: 'Alfie Stockton',
    teamId: 'sunday_xi',
    role: 'Bowler',
    matches: 7,
    innings: 5,
    runs: 55,
    highScore: '21',
    battingAverage: 11.0,
    hundreds: 0,
    fifties: 0,
    oversBowled: 38,
    wickets: 13,
    fiveWickets: 1,
    bestBowling: '5-20',
    bowlingAverage: 13.1,
    economy: 4.5,
    bowlingStyle: 'Right-arm fast-medium',
    bowlingType: 'seam',
    catches: 4,
    stumpings: 0,
  },
  {
    id: 'ms_4',
    name: 'Harrison Leigh',
    teamId: 'sunday_xi',
    role: 'Bowler',
    matches: 6,
    innings: 4,
    runs: 30,
    highScore: '14',
    battingAverage: 7.5,
    hundreds: 0,
    fifties: 0,
    oversBowled: 30,
    wickets: 8,
    fiveWickets: 0,
    bestBowling: '3-24',
    bowlingAverage: 16.5,
    economy: 4.4,
    bowlingStyle: 'Right-arm off-spin',
    bowlingType: 'spin',
    catches: 2,
    stumpings: 0,
  },
  {
    id: 'ms_8',
    name: 'Max Probert',
    teamId: 'sunday_xi',
    role: 'Bowler',
    matches: 6,
    innings: 4,
    runs: 42,
    highScore: '18*',
    battingAverage: 14.0,
    hundreds: 0,
    fifties: 0,
    oversBowled: 26,
    wickets: 6,
    fiveWickets: 0,
    bestBowling: '2-16',
    bowlingAverage: 18.0,
    economy: 4.15,
    bowlingStyle: 'Right-arm leg-spin',
    bowlingType: 'spin',
    catches: 3,
    stumpings: 0,
  },
];

export function calculateSpinVsSeamStats(stats: MalpasPlayerStats[]): SpinVsSeamBreakdown {
  const seamBowlers = stats.filter(s => s.bowlingType === 'seam' || (s.bowlingStyle && (s.bowlingStyle.toLowerCase().includes('fast') || s.bowlingStyle.toLowerCase().includes('medium'))));
  const spinBowlers = stats.filter(s => s.bowlingType === 'spin' || (s.bowlingStyle && s.bowlingStyle.toLowerCase().includes('spin')));

  const compute = (list: MalpasPlayerStats[]): SpinVsSeamCategoryStats => {
    let overs = 0;
    let wickets = 0;
    let runsConceded = 0;
    let bestBowling = '-';
    let maxWkts = -1;
    let minRuns = 999;

    list.forEach(b => {
      overs += b.oversBowled;
      wickets += b.wickets;
      const r = Math.round(b.oversBowled * b.economy);
      runsConceded += r;

      if (b.bestBowling && b.bestBowling.includes('-')) {
        const [wStr, rStr] = b.bestBowling.split('-');
        const w = parseInt(wStr, 10);
        const runs = parseInt(rStr, 10);
        if (!isNaN(w) && !isNaN(runs)) {
          if (w > maxWkts || (w === maxWkts && runs < minRuns)) {
            maxWkts = w;
            minRuns = runs;
            bestBowling = `${b.bestBowling} (${b.name})`;
          }
        }
      }
    });

    const average = wickets > 0 ? Number((runsConceded / wickets).toFixed(2)) : 0;
    const economy = overs > 0 ? Number((runsConceded / overs).toFixed(2)) : 0;

    return {
      overs: Math.round(overs * 10) / 10,
      wickets,
      runsConceded,
      average,
      economy,
      bestBowling: bestBowling === '-' ? 'N/A' : bestBowling,
      bowlerCount: list.length,
    };
  };

  return {
    seam: compute(seamBowlers),
    spin: compute(spinBowlers),
  };
}

export const MALPAS_CLUB_RECORDS: MalpasClubRecord[] = [
  { category: 'Team High Score', recordTitle: 'Highest Innings Total', value: '312-5', holder: '1st XI', year: '2023', opponent: 'Kerridge CC' },
  { category: 'Individual High Score', recordTitle: 'Highest Individual Score', value: '154*', holder: 'Callum Andrews', year: '2024', opponent: 'Chester County Officers' },
  { category: 'Best Bowling Figures', recordTitle: 'Best Match Bowling', value: '8-19', holder: 'Edward Stockton', year: '2023', opponent: 'Bowdon Vale CC' },
  { category: 'Partnership Record', recordTitle: '1st Wicket Partnership', value: '204 runs', holder: 'C. Andrews & B. Wardle', year: '2024', opponent: 'Trafford Metrovics' },
  { category: 'Most Wickets in Season', recordTitle: 'Season Wicket Record', value: '48 wickets', holder: 'Edward Stockton', year: '2023' },
  { category: 'Most Runs in Season', recordTitle: 'Season Run Record', value: '845 runs', holder: 'Callum Andrews', year: '2024' },
];

export const MALPAS_NEWS_ARTICLES: MalpasNewsArticle[] = [
  {
    id: 'news-1',
    title: '1st XI Secure Thrilling 4-Wicket Victory Over Chester County Officers',
    subtitle: 'Callum Andrews (89*) and Edward Stockton (5-24) spark memorable away triumph in Cheshire League Div 4.',
    date: '2026-08-01',
    category: 'Match Report',
    teamId: '1st_xi',
    isFeatured: true,
    author: 'Malpas Press Bureau',
    imageUrl: '/images/hero_cricket_match.jpg',
    summary: 'A heroics-filled afternoon at Mannings Lane saw Malpas CC overcome a testing 182-run target with 10 balls to spare, spearheaded by captain Callum Andrews\' unblemished 89* and Edward Stockton\'s five-wicket haul.',
    scoreSummary: {
      homeScore: '181-9 (40.0 ov)',
      awayScore: '184-6 (38.2 ov)',
      result: 'Malpas CC won by 4 wickets',
    },
    matchHighlights: [
      { label: 'Top Batter', performer: 'Callum Andrews (89* off 74b, 10x4, 2x6)' },
      { label: 'Top Bowler', performer: 'Edward Stockton (5-24 in 8.0 ov)' },
      { label: 'Key Stand', performer: 'B. Wardle & C. Andrews (72 runs for 3rd Wicket)' },
    ],
    content: [
      'Malpas CC 1st XI continued their impressive surge up Cheshire Cricket League Division 4 on Saturday, holding their nerve in a high-intensity chase against Chester County Officers at Mannings Lane.',
      'Winning the toss and inserting the hosts, Malpas made early breakthroughs through fast bowler Dominic Dunning. However, it was leg-spinner Edward Stockton who turned the match on its head during the middle overs. Stockton ripped through Chester\'s middle order with precision, finishing with match-defining figures of 5 for 24 from his 8 overs.',
      'Chasing 182 for victory on a worn pitch, Malpas lost two quick wickets before opener Ben Wardle (42) and skipper Callum Andrews anchored the innings. Andrews delivered a masterclass in controlled aggression, accelerating through his half-century and striking 10 boundaries and 2 towering sixes to seal victory with 4 wickets in hand.',
      'The win elevates Malpas into the top 3 of Division 4 as the club prepares for next weekend\'s blockbuster clash against Bowdon Vale at The Recreation Ground.'
    ],
  },
  {
    id: 'news-2',
    title: 'Malpas Junior Academy Summer Festival & Coaching Camp Announced',
    subtitle: 'Open registration for U11, U13, and U15 players at Wrexham Road starting August 15.',
    date: '2026-08-05',
    category: 'Junior Academy',
    isFeatured: true,
    author: 'Youth Development Committee',
    imageUrl: '/images/cricket_pavilion.jpg',
    summary: 'Malpas CC is thrilled to launch our annual Summer Youth Festival, inviting young cricketers from across Cheshire West to build fundamental skills under ECB-certified coaches.',
    content: [
      'Following a fantastic turnout in our spring sessions, Malpas Cricket Club is proud to announce the 2026 Summer Coaching & Youth Festival at our historic Wrexham Road ground.',
      'Designed for boys and girls aged 7 to 15 of all ability levels, the 3-day summer camp will cover masterclasses in technical batting, bowling variations, athletic fielding, and live match situations.',
      'All sessions will be led by ECB Level 2 & 3 coaches, supported by senior 1st XI players. Each participant will receive a Malpas CC junior training shirt, personal progress card, and entry into the end-of-camp T20 showcase tournament.',
      'Registration is open now via the club portal or by contacting Youth Coordinator Richard Wardle.'
    ],
  },
  {
    id: 'news-3',
    title: 'Kerridge Swept Aside as Malpas 1st XI Post Dominant 215 Total at Home',
    subtitle: 'Flannery and Wardle star in 32-run victory at The Recreation Ground.',
    date: '2026-07-25',
    category: 'Match Report',
    teamId: '1st_xi',
    isFeatured: false,
    author: 'Match Day Media',
    imageUrl: '/images/hero_cricket_match.jpg',
    summary: 'A disciplined team performance anchored by Oliver Flannery\'s half-century ensured Malpas defended 215-7 against a tough Kerridge XI in front of a packed home pavilion crowd.',
    scoreSummary: {
      homeScore: '215-7 (40.0 ov)',
      awayScore: '183 all out (37.4 ov)',
      result: 'Malpas CC won by 32 runs',
    },
    matchHighlights: [
      { label: 'Top Batter', performer: 'Oliver Flannery (68 off 58b)' },
      { label: 'Top Bowler', performer: 'Dominic Dunning (3-18 in 7.4 ov)' },
      { label: 'Support', performer: 'Ben Wardle (48 off 52b)' },
    ],
    content: [
      'The Recreation Ground was bathed in sunshine on Saturday as Malpas 1st XI earned a comprehensive 32-run victory against Kerridge CC.',
      'Opting to bat first, Malpas constructed a formidable 215-7 in 40 overs. Oliver Flannery provided the fireworks with a brisk 68, ably supported by Ben Wardle (48) and late-order hitting from Harry Hughes (28*).',
      'In response, Kerridge started strongly before opening bowler Dominic Dunning unleashed an aggressive second spell, taking 3 wickets for 18 runs to bowl out the visitors for 183.'
    ],
  },
  {
    id: 'news-4',
    title: 'Pavilion Renovations & New Net Facilities Opening Event at Wrexham Road',
    subtitle: 'Club celebrates completion of upgraded practice nets and spectator terrace.',
    date: '2026-07-30',
    category: 'Club News',
    isFeatured: false,
    author: 'Club Committee',
    imageUrl: '/images/cricket_pavilion.jpg',
    summary: 'Malpas CC officially opens its refurbished pavilion terrace and state-of-the-art twin lane practice nets following successful community fundraising and grant support.',
    content: [
      'Malpas Cricket Club is delighted to invite all members, supporters, and local residents to our official Pavilion Opening Evening on Friday August 14th.',
      'Thanks to generous grants from the Cheshire Cricket Board and local donors, the club has completed a full restoration of the main clubhouse terrace, installed energy-efficient solar lighting, and laid brand new all-weather practice nets.',
      'The event will feature a ribbon-cutting ceremony, an intra-club T20 match under dusk lights, live barbecue, and refreshments at the pavilion bar.'
    ],
  },
  {
    id: 'news-5',
    title: '2nd XI Prevail in High-Stakes Chase Against Kerridge 2nd XI',
    subtitle: 'Skipper Richard Wardle unleashes unbeaten 76* to guide Malpas to 5-wicket win.',
    date: '2026-08-01',
    category: 'Match Report',
    teamId: '2nd_xi',
    isFeatured: false,
    author: '2nd XI Reporter',
    imageUrl: '/images/hero_cricket_match.jpg',
    summary: 'Richard Wardle played a captain\'s knock of 76 non-out as Malpas 2nd XI successfully chased down 143 runs at Wrexham Road with overs to spare.',
    scoreSummary: {
      homeScore: '145-5 (32.1 ov)',
      awayScore: '142-8 (40.0 ov)',
      result: 'Malpas 2nd XI won by 5 wickets',
    },
    matchHighlights: [
      { label: 'Match Winner', performer: 'Richard Wardle (76* off 64b)' },
      { label: 'Top Bowler', performer: 'Jack Millington (3-21 in 8.0 ov)' },
    ],
    content: [
      'Malpas 2nd XI turned in a clinical display at home against Kerridge 2nd XI in Cheshire Reserve Division 4.',
      'Restricting Kerridge to 142-8 thanks to disciplined spells from Jack Millington (3-21) and Peter Davies (2-28), Malpas made light work of the target.',
      'Skipper Richard Wardle struck 11 crisp boundaries in his undefeated 76, combining with Charlie Davenport (34) for an 88-run partnership that secured maximum points.'
    ],
  },
];

